sxw:
  elasticsearch:
    cluster-name: docker-cluster
    cluster-nodes: 192.168.2.180:9300,192.168.2.181:9300
    user-name: elastic
    password: changeme

com:
  sit:
    rocketmq:
      name-server: 182.168.80.20:9876
      topic: face-ll-0804
      group-name: default-009
      consume-thread-max: 10
      consume-thread-min: 5
      consume-pattern: old

sit:
  elasticsearch:
    clusterNodes: 172.20.32.192:9200

feign:
  hystrix:
    enabled: true